### ISSUE TITLE
麻烦加一下 IE的兼容处理，打包方式

### ISSUE THREAD

**Issue by appbest** [F-loat/mpvue-packager#3]
目前打包，在谷歌浏览器正常，在IE空白，安卓4.0 也是，主要是不支持 ES5

**Comment by appbest** [comment]
npm i -D babel-polyfill

build文件夹下webpack.base.conf.js在里面修改
`
module.exports = {
  entry: ["babel-polyfill", "./src/main.h5.js"]
}

`

在main.h5.js中添加：
import es6Promise from "babel-polyfill";
es6Promise .polyfill();

**Comment by F-loat** [comment]
这个暂时不考虑加，有需要的自定义配置即可

**Comment by F-loat** [comment]
另外 babel-polyfill 在打包入口或代码里引用一次即可

**Comment by appbest** [comment]
要怎么配置，IE 全线报错，android 4.3 也打不开。
同样代码，在其它脚手架里面显示正常
请指点一下

**Comment by F-loat** [comment]
https://babeljs.io/docs/en/babel-polyfill/

**Comment by F-loat** [comment]
webpack 的 entry 你可以覆盖掉的啊，而且在代码里引用也可以，官方推荐的是在 .babelrc 里配置，这个可能有问题，我后面处理下

**Comment by appbest** [comment]
本地调试，显示正常，打包后就报错了，样式也有点乱

**Comment by F-loat** [comment]
报错请把错误发一下。。

**Comment by appbest** [comment]
测试的 ithome 项目，dev 和 build 模式下都是

IE  浏览器不显示，并且报错

SCRIPT1028: 缺少标识符、字符串或数字
main.js (1630,1)

安卓手机也是空白，没有错误

**Comment by F-loat** [comment]
ithome 这个项目在 ie 下的问题主要是引用了 xmlstring2json 这个库造成的，正常情况下加了 polyfill 还是能支持到 ie9 的

**Comment by F-loat** [comment]
https://github.com/F-loat/ithome-lite/commit/30b41be55334346484c131e76b76f183e638b769
