### ISSUE TITLE
建议，postCss 应该在 px2rpx-loader之前作用吧

### ISSUE THREAD

**Issue by voodeng** [F-loat/mpvue-packager#6]
首先，感谢一哈，用这个包package.json一下干净多了。

看了下配置
https://github.com/F-loat/mpvue-packager/blob/master/lib/utils.js#L66-L72

如果先转换成了rpx，那么处理px的postCSS插件就没法用了

**Comment by F-loat** [comment]
这两个确实换下顺序好点，我改下，不急用的话后面再发版了
